import sys
from typing import Any

from spy.cli.cli import app


def pyproject_entry_point() -> Any:
    """
    This is called by the script generated by pyproject.toml
    """
    if sys.platform == "emscripten":
        print(
            "The 'spy' command does not work in a pyodide venv running under node. "
            "Please use python -m spy"
        )
        sys.exit(1)
    return app()
