import sys
from typing import Any

from spy.cli.commands.build import build
from spy.cli.commands.cleanup import cleanup
from spy.cli.commands.execute import execute
from spy.cli.commands.imports import imports
from spy.cli.commands.parse import parse
from spy.cli.commands.pyparse import pyparse
from spy.cli.commands.redshift import redshift
from spy.cli.commands.symtable import symtable
from spy.cli.spy_typer import AppGroupConfig, SpyTyper

app = SpyTyper(pretty_exceptions_enable=False, cls=AppGroupConfig, no_args_is_help=True)

# Commands
# Each command should be written as an async function which takes
# a single dataclass as its only argument
# Aliases may be created by separating multiple names with , or |

# This is the order commands will appear in the --help

app.spy_command(execute, name="x | execute", default=True)
app.spy_command(build, name="b | build")
app.spy_command(pyparse, name="y | pyparse")
app.spy_command(parse, name="p | parse")
app.spy_command(imports, name="I | imports")
app.spy_command(symtable, name="s | symtable")
app.spy_command(redshift, name="r | redshift")
app.spy_command(cleanup, name="c | cleanup")


def pyproject_entry_point() -> Any:
    """
    This is called by the script generated by pyproject.toml
    """
    if sys.platform == "emscripten":
        print(
            "The 'spy' command does not work in a pyodide venv running under node. "
            "Please use python -m spy"
        )
        sys.exit(1)
    return app()
