from types import NoneType
from typing import TYPE_CHECKING

from spy import ast
from spy.backend.c import c_ast as C
from spy.backend.c.context import C_Ident, C_Type, Context
from spy.fqn import FQN
from spy.location import Loc
from spy.textbuilder import TextBuilder
from spy.util import magic_dispatch, shortrepr
from spy.vm.b import TYPES
from spy.vm.builtin import IRTag
from spy.vm.function import W_ASTFunc, W_Func
from spy.vm.modules.unsafe.ptr import W_Ptr

if TYPE_CHECKING:
    from spy.backend.c.cmodwriter import CModuleWriter


class CFuncWriter:
    ctx: Context
    cmodw: "CModuleWriter"
    tbc: TextBuilder
    fqn: FQN
    w_func: W_ASTFunc
    last_emitted_linenos: tuple[int, int]

    def __init__(
        self, ctx: Context, cmodw: "CModuleWriter", fqn: FQN, w_func: W_ASTFunc
    ) -> None:
        self.ctx = ctx
        self.cmodw = cmodw
        self.tbc = cmodw.tbc
        self.fqn = fqn
        self.w_func = w_func
        self.last_emitted_linenos = (-1, -1)  # see emit_lineno_maybe
        self._temp_var_counter = 0

    def ppc(self) -> None:
        """
        Pretty print the C code generated so far
        """
        print(self.tbc.build())

    def ppast(self) -> None:
        """
        Pretty print the AST
        """
        self.w_func.funcdef.pp()

    def emit(self) -> None:
        """
        Emit the code for the whole function
        """
        self.emit_lineno(self.w_func.funcdef.loc.line_start)
        c_func = self.ctx.c_function(self.fqn.c_name, self.w_func)
        self.tbc.wl(c_func.decl() + " {")
        with self.tbc.indent():
            self.emit_local_vars()
            for stmt in self.w_func.funcdef.body:
                self.emit_stmt(stmt)

            if self.w_func.w_functype.w_restype is not TYPES.w_NoneType:
                # this is a non-void function: if we arrive here, it means we
                # reached the end of the function without a return. Ideally,
                # we would like to also report an error message, but for now
                # we just abort.
                msg = "reached the end of the function without a `return`"
                self.tbc.wl(f"abort(); /* {msg} */")
        self.tbc.wl("}")

    def emit_local_vars(self) -> None:
        """
        Declare all local variables.

        We need to declare all of them in advance because C scoping rules are
        different than SPy scoping rules, so we emit the C declaration when we
        see e.g. a VarDef.
        """
        assert self.w_func.locals_types_w is not None
        param_names = [arg.name for arg in self.w_func.funcdef.args]
        for varname, w_T in self.w_func.locals_types_w.items():
            c_type = self.ctx.w2c(w_T)
            if (
                varname not in ("@return", "@if", "@and", "@or", "@while", "@assert")
                and varname not in param_names
            ):
                c_varname = C_Ident(varname)
                self.tbc.wl(f"{c_type} {c_varname};")

    def _new_temp_var(self, c_type: C_Type) -> str:
        param_names = {arg.name for arg in self.w_func.funcdef.args}
        locals_types = self.w_func.locals_types_w or {}
        locals_names = set(locals_types)
        reserved = param_names | locals_names
        while True:
            varname = f"spy_tmp{self._temp_var_counter}"
            self._temp_var_counter += 1
            if varname not in reserved:
                break
        self.tbc.wl(f"{c_type} {C_Ident(varname)};")
        return varname

    def _call_codegen_args(self, call: ast.Call, irtag: IRTag) -> list[ast.Expr]:
        # see unsafe/ptr.py::w_GETITEM and w_SETITEM there, we insert an
        # extra "w_loc" argument, which is not needed by the C backend
        # because we rely on C's own mechanism to get line numbers.
        # Moreover, we don't have a way to render "W_Loc" consts to C.
        #
        # So, we ignore the trailing argument. Note that this must match
        # with the signature of the load/store functions generated by
        # unsafe.h:SPY_PTR_FUNCTIONS.
        if irtag.tag in ("ptr.getitem", "ptr.store"):
            assert call.args and isinstance(call.args[-1], ast.LocConst)
            return call.args[:-1]
        return call.args

    def _call_arg_types_for_temps(
        self, w_func: W_Func, args: list[ast.Expr]
    ) -> list[C_Type]:
        param_iter = w_func.w_functype.all_params()
        c_types: list[C_Type] = []
        for _ in args:
            try:
                param = next(param_iter)
            except StopIteration:
                assert False, "param/arg mismatch"
            c_types.append(self.ctx.w2c(param.w_T))
        return c_types

    # ==============

    def emit_lineno_maybe(self, loc: Loc) -> None:
        """
        Emit a #line directive, but only if it's needed.
        """
        # line numbers corresponding to the last emitted #line
        last_spy, last_c = self.last_emitted_linenos
        #
        # line numbers as they are understood by the C compiler, i.e. what
        # goes to debuginfo if we don't emit a new #line
        cur_c = self.tbc.lineno
        cur_spy = last_spy + (cur_c - last_c) - 1
        #
        # desired spy line number, i.e. what we would like it to be
        desired_spy = loc.line_start
        if desired_spy != cur_spy:
            # time to emit a new #line directive
            self.emit_lineno(desired_spy)

    def emit_lineno(self, spyline: int) -> None:
        """
        Emit a #line directive, unconditionally
        """
        if self.cmodw.c_mod.spyfile is None:
            # we don't have an associated spyfile, so we cannot emit SPY_LINE
            return
        cline = self.tbc.lineno
        self.tbc.wl(f"#line SPY_LINE({spyline}, {cline})")
        self.last_emitted_linenos = (spyline, cline)

    def emit_stmt(self, stmt: ast.Stmt) -> None:
        self.emit_lineno_maybe(stmt.loc)
        magic_dispatch(self, "emit_stmt", stmt)

    def fmt_expr(self, expr: ast.Expr) -> C.Expr:
        # XXX: here we should probably handle typeconv, if present.
        # However, we cannot yet write a test for it because:
        #   - we cannot test DynamicCast because we don't support object
        #   - we cannot test NumericConv because the expressions are
        #     automatically converted by the C compiler anyway
        return magic_dispatch(self, "fmt_expr", expr)

    def lower_expr(self, expr: ast.Expr) -> tuple[list[C.Expr], C.Expr]:
        """
        Lower an expression to:
          - a list of expression-statements to emit before using it
          - the final expression value
        """
        method = getattr(self, f"lower_expr_{expr.__class__.__name__}", None)
        if method is not None:
            return method(expr)
        return [], self.fmt_expr(expr)

    def _emit_expr_prelude(self, prelude: list[C.Expr]) -> None:
        for expr in prelude:
            self.tbc.wl(f"{expr};")

    # ===== statements =====

    def emit_stmt_Pass(self, stmt: ast.Pass) -> None:
        pass

    def emit_stmt_Break(self, stmt: ast.Break) -> None:
        self.tbc.wl("break;")

    def emit_stmt_Continue(self, stmt: ast.Continue) -> None:
        self.tbc.wl("continue;")

    def emit_stmt_Return(self, ret: ast.Return) -> None:
        prelude, v = self.lower_expr(ret.value)
        self._emit_expr_prelude(prelude)
        if v is C.Void():
            self.tbc.wl("return;")
        else:
            self.tbc.wl(f"return {v};")

    def emit_stmt_VarDef(self, vardef: ast.VarDef) -> None:
        # NOTE: the local variable declaration happens in emit_local_vars, here we just
        # assign the value
        if vardef.value:
            target = C_Ident(vardef.name.value)
            prelude, v = self.lower_expr(vardef.value)
            self._emit_expr_prelude(prelude)
            self.tbc.wl(f"{target} = {v};")

    def emit_stmt_Assign(self, assign: ast.Assign) -> None:
        assert False, "ast.Assign nodes should not survive redshifting"

    def emit_stmt_AssignLocal(self, assign: ast.AssignLocal) -> None:
        target = assign.target.value
        prelude, v = self.lower_expr(assign.value)
        self._emit_expr_prelude(prelude)
        c_varname = C_Ident(target)
        self.tbc.wl(f"{c_varname} = {v};")

    def emit_stmt_AssignCell(self, assign: ast.AssignCell) -> None:
        prelude, v = self.lower_expr(assign.value)
        self._emit_expr_prelude(prelude)
        target = assign.target_fqn.c_name
        c_varname = C_Ident(target)
        self.tbc.wl(f"{c_varname} = {v};")

    def emit_stmt_StmtExpr(self, stmt: ast.StmtExpr) -> None:
        prelude, v = self.lower_expr(stmt.value)
        self._emit_expr_prelude(prelude)
        if v is C.Void():
            pass
        else:
            self.tbc.wl(f"{v};")

    def emit_stmt_If(self, if_node: ast.If) -> None:
        prelude, test = self.lower_expr(if_node.test)
        self._emit_expr_prelude(prelude)
        self.tbc.wl(f"if ({test})" + "{")
        with self.tbc.indent():
            for stmt in if_node.then_body:
                self.emit_stmt(stmt)
        #
        if if_node.else_body:
            self.tbc.wl("} else {")
            with self.tbc.indent():
                for stmt in if_node.else_body:
                    self.emit_stmt(stmt)
        #
        self.tbc.wl("}")

    def emit_stmt_While(self, while_node: ast.While) -> None:
        prelude, test = self.lower_expr(while_node.test)
        if not prelude:
            self.tbc.wl(f"while ({test}) " + "{")
            with self.tbc.indent():
                for stmt in while_node.body:
                    self.emit_stmt(stmt)
            self.tbc.wl("}")
            return

        # Re-evaluate test prelude every iteration in order
        self.tbc.wl("while (1) {")
        with self.tbc.indent():
            self._emit_expr_prelude(prelude)
            self.tbc.wl(f"if (!({test})) " + "{")
            with self.tbc.indent():
                self.tbc.wl("break;")
            self.tbc.wl("}")
            for stmt in while_node.body:
                self.emit_stmt(stmt)
        self.tbc.wl("}")

    def emit_stmt_Assert(self, assert_node: ast.Assert) -> None:
        prelude, test = self.lower_expr(assert_node.test)
        self._emit_expr_prelude(prelude)
        self.tbc.wl(f"if (!({test}))" + " {")
        with self.tbc.indent():
            if assert_node.msg is not None:
                # TODO: assuming msg is always a string. extend the logic to work with other types
                msg_prelude, msg = self.lower_expr(assert_node.msg)
                self._emit_expr_prelude(msg_prelude)
                self.tbc.wl(
                    f'spy_panic("AssertionError", ({msg})->utf8, '
                    f'"{assert_node.loc.filename}", {assert_node.loc.line_start});'
                )
            else:
                self.tbc.wl(
                    f'spy_panic("AssertionError", "assertion failed", '
                    f'"{assert_node.loc.filename}", {assert_node.loc.line_start});'
                )

        self.tbc.wl("}")

    # ===== expressions =====

    def fmt_expr_Constant(self, const: ast.Constant) -> C.Expr:
        # unsupported literals are rejected directly by the parser, see
        # Parser.from_py_expr_Constant
        T = type(const.value)
        assert T in (int, float, bool, str, NoneType)
        if T is NoneType:
            return C.Void()
        elif T is int:
            return C.Literal(str(const.value))
        elif T is float:
            return C.Literal(str(const.value))
        elif T is bool:
            return C.Literal(str(const.value).lower())
        else:
            raise NotImplementedError("WIP")

    def fmt_expr_StrConst(self, const: ast.StrConst) -> C.Expr:
        # SPy string literals must be initialized as C globals. We want to
        # generate the following:
        #
        #     // global declarations
        #     static spy_Str SPY_g_str0 = {5, "hello"};
        #     ...
        #     // literal expr
        #     &SPY_g_str0 /* "hello" */
        #
        # Note that in the literal expr we also put a comment showing what is
        # the content of the literal: hopefully this will make the code more
        # readable for humans.
        #
        # Emit the global decl
        s = const.value
        utf8 = s.encode("utf-8")
        v = self.cmodw.new_global_var("str")  # SPY_g_str0
        n = len(utf8)
        lit = C.Literal.from_bytes(utf8)
        init = "{%d, %s}" % (n, lit)
        self.cmodw.tbc_globals.wl(f"static spy_Str {v} = {init};")
        #
        # shortstr is what we show in the comment, with a length limit
        comment = shortrepr(utf8.decode("utf-8"), 15)
        v = f"{v} /* {comment} */"
        return C.UnaryOp("&", C.Literal(v))

    def fmt_expr_FQNConst(self, const: ast.FQNConst) -> C.Expr:
        w_obj = self.ctx.vm.lookup_global(const.fqn)
        if isinstance(w_obj, W_Ptr):
            # for each PtrType, we emit the corresponding NULL define with the
            # appropriate fqn name, see Context.new_ptr_type
            assert w_obj.addr == 0, "only NULL ptrs can be constants"
            return C.Literal(const.fqn.c_name)
        elif isinstance(w_obj, W_Func):
            return C.Literal(const.fqn.c_name)
        else:
            assert False

    def fmt_expr_Name(self, name: ast.Name) -> C.Expr:
        assert False, "ast.Name nodes should not survive redshifting"

    def fmt_expr_NameLocalDirect(self, name: ast.NameLocalDirect) -> C.Expr:
        varname = C_Ident(name.sym.name)
        return C.Literal(f"{varname}")

    def fmt_expr_NameOuterCell(self, name: ast.NameOuterCell) -> C.Expr:
        return C.Literal(name.fqn.c_name)

    def fmt_expr_NameOuterDirect(self, name: ast.NameOuterDirect) -> C.Expr:
        # at the moment of writing, closed-over variables are always blue, so
        # they should not survive redshifting
        assert False, "unexepcted NameOuterDirect"

    def fmt_expr_AssignExpr(self, assignexpr: ast.AssignExpr) -> C.Expr:
        return self._fmt_assignexpr(assignexpr.target.value, assignexpr.value)

    def fmt_expr_AssignExprLocal(self, assignexpr: ast.AssignExprLocal) -> C.Expr:
        return self._fmt_assignexpr(assignexpr.target.value, assignexpr.value)

    def fmt_expr_AssignExprCell(self, assignexpr: ast.AssignExprCell) -> C.Expr:
        return self._fmt_assignexpr(assignexpr.target_fqn.c_name, assignexpr.value)

    def _assign_target_expr(self, target: str) -> C.Expr:
        return C.Literal(f"{C_Ident(target)}")

    def _fmt_assignexpr_from_c_expr(self, target: str, value: C.Expr) -> C.Expr:
        return C.BinOp("=", self._assign_target_expr(target), value)

    def _fmt_assignexpr(self, target: str, value_expr: ast.Expr) -> C.Expr:
        value = self.fmt_expr(value_expr)
        return self._fmt_assignexpr_from_c_expr(target, value)

    def _lower_assignexpr(
        self, target: str, value_expr: ast.Expr
    ) -> tuple[list[C.Expr], C.Expr]:
        prelude, value = self.lower_expr(value_expr)
        prelude.append(self._fmt_assignexpr_from_c_expr(target, value))
        return prelude, self._assign_target_expr(target)

    def lower_expr_AssignExpr(
        self, assignexpr: ast.AssignExpr
    ) -> tuple[list[C.Expr], C.Expr]:
        return self._lower_assignexpr(assignexpr.target.value, assignexpr.value)

    def lower_expr_AssignExprLocal(
        self, assignexpr: ast.AssignExprLocal
    ) -> tuple[list[C.Expr], C.Expr]:
        return self._lower_assignexpr(assignexpr.target.value, assignexpr.value)

    def lower_expr_AssignExprCell(
        self, assignexpr: ast.AssignExprCell
    ) -> tuple[list[C.Expr], C.Expr]:
        return self._lower_assignexpr(assignexpr.target_fqn.c_name, assignexpr.value)

    def fmt_expr_BinOp(self, binop: ast.BinOp) -> C.Expr:
        raise NotImplementedError(
            "ast.BinOp not supported. It should have been redshifted away"
        )

    def fmt_expr_And(self, op: ast.And) -> C.Expr:
        l = self.fmt_expr(op.left)
        r = self.fmt_expr(op.right)
        return C.BinOp("&&", l, r)

    def fmt_expr_Or(self, op: ast.Or) -> C.Expr:
        l = self.fmt_expr(op.left)
        r = self.fmt_expr(op.right)
        return C.BinOp("||", l, r)

    def lower_expr_And(self, op: ast.And) -> tuple[list[C.Expr], C.Expr]:
        l_prelude, l = self.lower_expr(op.left)
        r_prelude, r = self.lower_expr(op.right)
        l_expr = self._chain_commas(l_prelude + [l]) if l_prelude else l
        r_expr = self._chain_commas(r_prelude + [r]) if r_prelude else r
        return [], C.BinOp("&&", l_expr, r_expr)

    def lower_expr_Or(self, op: ast.Or) -> tuple[list[C.Expr], C.Expr]:
        l_prelude, l = self.lower_expr(op.left)
        r_prelude, r = self.lower_expr(op.right)
        l_expr = self._chain_commas(l_prelude + [l]) if l_prelude else l
        r_expr = self._chain_commas(r_prelude + [r]) if r_prelude else r
        return [], C.BinOp("||", l_expr, r_expr)

    FQN2BinOp = {
        FQN("operator::i8_add"): "+",
        FQN("operator::i8_sub"): "-",
        FQN("operator::i8_mul"): "*",
        FQN("operator::i8_lshift"): "<<",
        FQN("operator::i8_rshift"): ">>",
        FQN("operator::i8_and"): "&",
        FQN("operator::i8_or"): "|",
        FQN("operator::i8_xor"): "^",
        FQN("operator::i8_eq"): "==",
        FQN("operator::i8_ne"): "!=",
        FQN("operator::i8_lt"): "<",
        FQN("operator::i8_le"): "<=",
        FQN("operator::i8_gt"): ">",
        FQN("operator::i8_ge"): ">=",
        #
        FQN("operator::u8_add"): "+",
        FQN("operator::u8_sub"): "-",
        FQN("operator::u8_mul"): "*",
        FQN("operator::u8_lshift"): "<<",
        FQN("operator::u8_rshift"): ">>",
        FQN("operator::u8_and"): "&",
        FQN("operator::u8_or"): "|",
        FQN("operator::u8_xor"): "^",
        FQN("operator::u8_eq"): "==",
        FQN("operator::u8_ne"): "!=",
        FQN("operator::u8_lt"): "<",
        FQN("operator::u8_le"): "<=",
        FQN("operator::u8_gt"): ">",
        FQN("operator::u8_ge"): ">=",
        #
        FQN("operator::i32_add"): "+",
        FQN("operator::i32_sub"): "-",
        FQN("operator::i32_mul"): "*",
        FQN("operator::i32_lshift"): "<<",
        FQN("operator::i32_rshift"): ">>",
        FQN("operator::i32_and"): "&",
        FQN("operator::i32_or"): "|",
        FQN("operator::i32_xor"): "^",
        FQN("operator::i32_eq"): "==",
        FQN("operator::i32_ne"): "!=",
        FQN("operator::i32_lt"): "<",
        FQN("operator::i32_le"): "<=",
        FQN("operator::i32_gt"): ">",
        FQN("operator::i32_ge"): ">=",
        #
        FQN("operator::u32_add"): "+",
        FQN("operator::u32_sub"): "-",
        FQN("operator::u32_mul"): "*",
        FQN("operator::u32_lshift"): "<<",
        FQN("operator::u32_rshift"): ">>",
        FQN("operator::u32_and"): "&",
        FQN("operator::u32_or"): "|",
        FQN("operator::u32_xor"): "^",
        FQN("operator::u32_eq"): "==",
        FQN("operator::u32_ne"): "!=",
        FQN("operator::u32_lt"): "<",
        FQN("operator::u32_le"): "<=",
        FQN("operator::u32_gt"): ">",
        FQN("operator::u32_ge"): ">=",
        #
        FQN("operator::f64_add"): "+",
        FQN("operator::f64_sub"): "-",
        FQN("operator::f64_mul"): "*",
        FQN("unsafe::f64_ieee754_div"): "/",
        FQN("operator::f64_eq"): "==",
        FQN("operator::f64_ne"): "!=",
        FQN("operator::f64_lt"): "<",
        FQN("operator::f64_le"): "<=",
        FQN("operator::f64_gt"): ">",
        FQN("operator::f64_ge"): ">=",
        # the following are NOT special cased, and are implemented in
        # operator.h. They are listed here to make emphasize that they are not
        # omitted from above by mistake:
        # T is any of the following types: i8, u8, i32, u32, f32 and f64
        # FQN('operator::T_div')
        # FQN('operator::T_floordiv')
        # FQN('operator::T_mod')
        # FQN('unsafe::T_unchecked_div')
        # FQN('unsafe::T_unchecked_floordiv')
        # FQN('unsafe::T_unchecked_mod')
    }

    FQN2UnaryOp = {
        FQN("operator::i8_neg"): "-",
        FQN("operator::i32_neg"): "-",
        FQN("operator::f64_neg"): "-",
    }

    def _chain_commas(self, exprs: list[C.Expr]) -> C.Expr:
        assert exprs
        acc = exprs[0]
        for expr in exprs[1:]:
            acc = C.BinOp(",", acc, expr)
        return C.Literal(f"({acc})")

    def _lower_call_args_to_temps(
        self, w_func: W_Func, args: list[ast.Expr]
    ) -> tuple[list[C.Expr], list[C.Expr]]:
        c_types = self._call_arg_types_for_temps(w_func, args)
        assert len(c_types) == len(args), "param/arg mismatch"
        prelude: list[C.Expr] = []
        c_args: list[C.Expr] = []
        for arg, c_type in zip(args, c_types, strict=True):
            arg_prelude, arg_value = self.lower_expr(arg)
            prelude.extend(arg_prelude)
            if c_type.name == "void":
                # NoneType arguments have no C-level value
                if arg_value is not C.Void():
                    prelude.append(arg_value)
                c_args.append(C.Void())
                continue
            temp_name = self._new_temp_var(c_type)
            temp_expr = C.Literal(f"{C_Ident(temp_name)}")
            prelude.append(C.BinOp("=", temp_expr, arg_value))
            c_args.append(temp_expr)
        return prelude, c_args

    def _fmt_generic_call_with_c_args(self, fqn: FQN, c_args: list[C.Expr]) -> C.Expr:
        self.ctx.add_include_maybe(fqn)
        return C.Call(fqn.c_name, c_args)

    def _fmt_struct_make_with_c_args(self, fqn: FQN, c_args: list[C.Expr]) -> C.Expr:
        c_structtype = self.ctx.c_restype_by_fqn(fqn)
        strargs = ", ".join(str(arg) for arg in c_args if arg is not C.Void())
        return C.Cast(c_structtype, C.Literal("{ %s }" % strargs))

    def _fmt_ptr_setfield_with_c_args(
        self, call: ast.Call, c_args: list[C.Expr]
    ) -> C.Expr:
        assert isinstance(call.args[1], ast.StrConst)
        c_ptr = c_args[0]
        attr = call.args[1].value
        offset = call.args[2]  # ignored
        c_lval = C.PtrField(c_ptr, attr)
        c_rval = c_args[3]
        return C.BinOp("=", c_lval, c_rval)

    def _fmt_ptr_getfield_with_ptr(
        self, fqn: FQN, call: ast.Call, c_ptr: C.Expr
    ) -> C.Expr:
        irtag = self.ctx.vm.get_irtag(fqn)
        assert isinstance(call.args[1], ast.StrConst)
        attr = call.args[1].value
        offset = call.args[2]  # ignored
        c_field = C.PtrField(c_ptr, attr)
        if irtag.data["by"] == "byref":
            c_restype = self.ctx.c_restype_by_fqn(fqn)
            return C.PtrFieldByRef(c_restype, c_field)
        return c_field

    def _fmt_struct_getfield_with_struct(self, fqn: FQN, c_struct: C.Expr) -> C.Expr:
        irtag = self.ctx.vm.get_irtag(fqn)
        name = irtag.data["name"]
        return C.Dot(c_struct, name)

    def fmt_expr_Call(self, call: ast.Call) -> C.Expr:
        prelude, expr = self.lower_expr_Call(call)
        if prelude:
            return self._chain_commas(prelude + [expr])
        return expr

    def lower_expr_Call(self, call: ast.Call) -> tuple[list[C.Expr], C.Expr]:
        assert isinstance(call.func, ast.FQNConst), (
            "indirect calls are not supported yet"
        )
        fqn = call.func.fqn

        irtag = self.ctx.vm.get_irtag(fqn)
        if call.func.fqn.modname == "jsffi":
            self.cmodw.emit_jsffi_error_maybe()

        if irtag.tag == "struct.getfield":
            assert len(call.args) == 1
            prelude, c_struct = self.lower_expr(call.args[0])
            return prelude, self._fmt_struct_getfield_with_struct(fqn, c_struct)

        if irtag.tag == "ptr.getfield":
            prelude, c_ptr = self.lower_expr(call.args[0])
            return prelude, self._fmt_ptr_getfield_with_ptr(fqn, call, c_ptr)

        args = self._call_codegen_args(call, irtag)
        w_obj = self.ctx.vm.lookup_global(fqn)
        assert isinstance(w_obj, W_Func), "calls should target functions after redshift"
        prelude, c_args = self._lower_call_args_to_temps(w_obj, args)

        if op := self.FQN2BinOp.get(fqn):
            assert len(c_args) == 2
            return prelude, C.BinOp(op, c_args[0], c_args[1])

        if op := self.FQN2UnaryOp.get(fqn):
            assert len(c_args) == 1
            return prelude, C.UnaryOp(op, c_args[0])

        if irtag.tag == "struct.make":
            return prelude, self._fmt_struct_make_with_c_args(fqn, c_args)

        if irtag.tag == "ptr.setfield":
            return prelude, self._fmt_ptr_setfield_with_c_args(call, c_args)

        if irtag.tag == "ptr.deref":
            # this is not strictly necessary as it's just a generic call, but
            # we handle ptr.deref explicitly for extra clarity.
            return prelude, self._fmt_generic_call_with_c_args(fqn, c_args)

        if irtag.tag in ("ptr.getitem", "ptr.store"):
            # c_args already has the synthetic trailing w_loc stripped by
            # _call_codegen_args.
            return prelude, self._fmt_generic_call_with_c_args(fqn, c_args)

        return prelude, self._fmt_generic_call_with_c_args(fqn, c_args)
