from typing import Any

class LocalPath:

    def dirpath(self, *args: Any) -> LocalPath: ...
    def check(self, *args: Any, **kwargs: Any) -> bool: ...
    def write(self, s: str) -> None: ...
    def read(self) -> str: ...
    def join(self, *args: str) -> LocalPath: ...

    purebasename: str


def local(x: Any) -> LocalPath: ...
