"""
mkdocs hook: auto-generate documentation pages from the .spy example files.

For every directory under examples/ whose name starts with a digit, this
generates one Markdown page under docs/src/examples/<dirname>.md,
containing one section per example:

  - the module docstring of the .spy file, rendered as prose
    ("Things to notice: ...")
  - the source code (with the docstring stripped, since it's already shown
    above as prose)
  - the corresponding saved output from examples/expected_output/

The order of the examples within a page follows the order in which they are
listed in playground/pyscript.toml.

The generated pages are build artifacts: they are written into docs_dir on
every build and are not committed to the repository.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path
from textwrap import dedent
from typing import NamedTuple

REPO_ROOT = Path(__file__).resolve().parent.parent
EXAMPLES_DIR = REPO_ROOT / "examples"
EXPECTED_OUTPUT_DIR = EXAMPLES_DIR / "expected_output"
PYSCRIPT_TOML = REPO_ROOT / "playground" / "pyscript.toml"
README = EXAMPLES_DIR / "README.md"

# Where the generated pages are written, relative to the mkdocs docs_dir.
OUTPUT_SUBDIR = "examples"

_GENERATED_BANNER = """\
<!--
  This page is auto-generated by examples/gen_doc_pages.py from the .spy
  files in examples/{dirname}/, in the order defined by
  playground/pyscript.toml. Do not edit by hand: edit the example files (or
  the hook) instead, then rebuild the docs.
-->
"""


class Example(NamedTuple):
    path: Path  # absolute path to the .spy file
    docstring: str | None  # module docstring, dedented
    code: str  # source code with the leading docstring stripped
    output: str | None  # saved output


def _numbered_categories_in_order() -> dict[str, list[str]]:
    """Return {dirname: [source_path, ...]} in the order given by pyscript.toml.

    Only directories directly under examples/ whose name starts with a digit
    are considered (e.g. "1_high_level"), matching the convention documented
    in examples/README.md.
    """
    config = tomllib.loads(PYSCRIPT_TOML.read_text())
    categories: dict[str, list[str]] = {}
    for source in config.get("files", {}):
        # e.g. "./examples/1_high_level/hello.spy"
        source_path = Path(source)
        if source_path.suffix != ".spy":
            continue
        try:
            rel = source_path.relative_to("examples")
        except ValueError:
            try:
                rel = Path(
                    *source_path.parts[source_path.parts.index("examples") + 1 :]
                )
            except ValueError:
                continue
        if len(rel.parts) < 2:
            continue
        dirname = rel.parts[0]
        if not dirname[:1].isdigit():
            continue
        categories.setdefault(dirname, []).append(rel.name)
    return categories


def _page_title(dirname: str) -> str:
    """ "1_high_level" -> "1 · High Level"."""
    num, _, rest = dirname.partition("_")
    words = rest.replace("_", " ").split()
    return f"{num} · {' '.join(w.capitalize() for w in words)}"


def _dir_descriptions() -> dict[str, str]:
    """Parse the {dirname: description} table out of examples/README.md."""
    if not README.exists():
        return {}
    descriptions = {}
    pattern = re.compile(r"\[`([\w.]+)/`\]\([^)]*\)\s*\|\s*(.+?)\s*\|\s*$")
    for line in README.read_text().splitlines():
        m = pattern.search(line)
        if m:
            descriptions[m.group(1)] = m.group(2)
    return descriptions


_DOCSTRING_RE = re.compile(r'^\s*("""|\'\'\')(.*?)\1[ \t]*\n?', re.DOTALL)
_LIST_ITEM_RE = re.compile(r"^\s*[-*]\s+")


def _fix_list_spacing(text: str) -> str:
    """Insert a blank line before a list that starts right after a lead-in line.

    The example docstrings often write:

        Things to notice:
          - first point
          - second point

    with no blank line between the lead-in sentence and the list. Python-
    Markdown only recognizes a list as its own block when it's preceded by a
    blank line; otherwise "  - first point" is treated as a lazy continuation
    of the previous paragraph and rendered as plain text. This inserts the
    blank line CommonMark-style renderers add implicitly, without touching
    already well-separated lists.
    """
    lines = text.splitlines()
    out: list[str] = []
    for i, line in enumerate(lines):
        if (
            _LIST_ITEM_RE.match(line)
            and i > 0
            and lines[i - 1].strip()
            and not _LIST_ITEM_RE.match(lines[i - 1])
        ):
            out.append("")
        out.append(line)
    return "\n".join(out)


def _split_docstring(source: str) -> tuple[str | None, str]:
    """Split a module docstring off the top of a .spy source file.

    Returns (docstring_text, remaining_code). remaining_code has leading
    blank lines (left after the docstring) trimmed.
    """
    m = _DOCSTRING_RE.match(source)
    if not m:
        return None, source.strip("\n")
    docstring = _fix_list_spacing(m.group(2).strip("\n"))
    rest = source[m.end() :].lstrip("\n")
    return docstring, rest.rstrip("\n")


def _load_example(dirname: str, filename: str) -> Example:
    path = EXAMPLES_DIR / dirname / filename
    source = path.read_text()
    docstring, code = _split_docstring(source)

    output_path = EXPECTED_OUTPUT_DIR / f"{path.stem}.txt"
    output = output_path.read_text() if output_path.exists() else None

    return Example(path=path, docstring=docstring, code=code, output=output)


def _render_page(dirname: str, filenames: list[str], description: str | None) -> str:
    parts = [_GENERATED_BANNER.format(dirname=dirname)]
    parts.append(f"# {_page_title(dirname)}\n")
    if description:
        parts.append(f"{description}\n")

    parts.append(
        dedent(
            f"""
        /// note
        This page is auto-generated from the examples in
        [`examples/{dirname}/`](https://github.com/spylang/spy/tree/main/examples/{dirname}).
        Want to play with these examples yourself?
        Try them in the [online playground](https://spylang.github.io/spy).
        ///
        """
        )
    )

    for filename in filenames:
        example = _load_example(dirname, filename)
        rel_path = f"examples/{dirname}/{filename}"

        parts.append(f"## `{filename}`\n")
        if example.docstring:
            parts.append(f"{example.docstring}\n")
        parts.append(f'```python title="{rel_path}"\n{example.code}\n```\n')
        if example.output is not None:
            parts.append(f"Output:\n\n```text\n{example.output}```\n")

    return "\n".join(parts)


def _generate(docs_dir: Path) -> None:
    output_dir = docs_dir / OUTPUT_SUBDIR
    output_dir.mkdir(parents=True, exist_ok=True)

    categories = _numbered_categories_in_order()
    descriptions = _dir_descriptions()

    for dirname, filenames in categories.items():
        page = _render_page(dirname, filenames, descriptions.get(dirname))
        (output_dir / f"{dirname}.md").write_text(page)


def on_pre_build(config, **kwargs):
    """mkdocs hook entry point: regenerate the example pages before each build."""
    _generate(Path(config["docs_dir"]))
