name: Preview Docs Builds

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone docs repository
        run: |
          git clone https://github.com/jeffersglass/spy.git /tmp/spy-docs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
           pip install .[docs]

      - name: Configure Git in docs repository
        working-directory: /tmp/spy-docs
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Build and deploy mkdocs
        working-directory:
        run: |
          mike deploy --config-file $GITHUB_WORKSPACE/docs/mkdocs.yml -b main --update-aliases preview --make-default
          mike make-default 

      - name: Get PR Info
        id: get_info
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          destination="pr-${PR_NUMBER}"
          echo "deploy_destination=$destination" >> "$GITHUB_OUTPUT"

      - name: "Deploy PR preview site"
        uses: peaceiris/actions-gh-pages@e9c66a37f080288a11235e32cbe2dc5fb3a679cc # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/spy-docs
          publish_branch: gh-pages
          destination_dir: ${{ steps.setup.outputs.deploy_destination}}
          keep_files: true
          force_orphan: false
          commit_message: "Publish PR preview #${{ github.event.pull_request.number }}"

      - name: "Comment PR Preview URL"
        uses: peter-evans/create-or-update-comment@v5.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Preview deployed: https://${{ github.repository_owner }}.github.io/${${{ github.repository }}/pr-${{ github.event.pull_request.number }}/