name: Preview Docs Builds

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
           pip install .[docs]

      - name: Configure Git in docs repository
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Build and deploy mkdocs
        run: |
          mike deploy preview --config-file docs/mkdocs.yml --update-aliases -b main --allow-empty
          mike set-default preview --config-file docs/mkdocs.yml -b main
          git checkout main
          git status
          git reset HEAD~1
          git status
          
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.8.1
        with:
          source-dir: docs/site/
          preview-branch: gh-pages
          qr-code: false