name: Preview Docs Builds

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone docs repository
        run: |
          git clone https://github.com/jeffersglass/spy.git /tmp/spy-docs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
           pip install .[docs]

      - name: Configure Git in docs repository
        working-directory: /tmp/spy-docs
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Build and deploy mkdocs
        working-directory: /tmp/spy-docs
        run: |
          mike deploy --config-file $GITHUB_WORKSPACE/docs/mkdocs.yml -b main --update-aliases preview

      - name: "Upload site artifact"
        id: artifact-upload-step
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: site
          path: docs/site
          if-no-files-found: error
          retention-days: 21
          include-hidden-files: true
          archive: false

      - name: "Comment PR preview URL"
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const previewUrl = `${{ steps.artifact-upload-step.outputs.artifact-url }}'`;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: context.issue.number,
              body: `Preview deployed: ${previewUrl}`,
            });