name: Playground and Example Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  playground-tests:
    name: playground-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libgc-dev

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true

      - name: Install venv
        run: |
          uv sync --locked

      - name: Build libspy
        run: |
          cd spy/libspy
          uv run make

      - name: Run playground tests
        run: |
          uv run pytest playground/tests/ -v

      - name: Run examples
        run: |
          uv run pytest -n auto examples
